<?php

return array(
	'id' => 'Page ID',
	'name' => 'Title',
	'title' => 'Title',
	'url' => 'URL',
	'template' => 'Template',
	'contents' => 'Content',
	'create' => Lang::get('labels.create_item', array(
    	'item' => Lang::choice('labels.page', 1),
    )),
    'url_will_be_autogenerated' => 'Will be auto-generated if left blank.',
    'description' => 'The main content of the application.',
    'empty_table' => 'Nothing here yet!',
    'create_friendly' => 'Add a page now',
);
