<?php

$title_input = array(
	'name' => 'title',
	'attr' => array(
		'autofocus',
	),
	'label' => Lang::get('pages.name'),
	'value' => isset($page) && $page->exists() ? $page->title : FALSE,
);

$url_input = array(
	'name' => 'url',
	'attr' => array(
		'placeholder' => Lang::get('pages.url_will_be_autogenerated'),
	),
	'label' => Lang::get('pages.url'),
	'value' => isset($page) && $page->exists() ? $page->url : FALSE,
);

?>
@include('forms.input', $title_input)
@include('forms.input', $url_input)

