<?php

$title_input = array(
	'name' => 'title',
	'attr' => array(
		'autofocus',
	),
	'help_text' => Lang::get('pages.title_usage'),
	'label' => Lang::get('pages.name'),
	'value' => isset($page) && $page->exists() ? $page->title : FALSE,
);

$url_input = array(
	'name' => 'url',
	'attr' => array(
		'placeholder' => Lang::get('pages.url_will_be_autogenerated'),
	),
	'prefix' => url('/') . '/',
	'label' => Lang::get('pages.url'),
	'value' => isset($page) && $page->exists() ? $page->url : FALSE,
);

?>
@include('forms.input', $title_input)
@include('forms.input', $url_input)
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
			@lang('pages.contents')
		</h3>
	</div>
	<div class="panel-body">
		@include('pages.template_form')
	</div>
</div>
